DATA:
  SIZE: [384,128]
  BPE_PATH: './data/bpe_simple_vocab_16e6.txt.gz'
  TRAIN_JSON_PATH: 'reid_raw.json'
  NUM_NEGS: 3

MODEL:
  NAME: 'clip_multigrained'
  BASE_MODEL: 'clip'
  PRETRAINED: 'ViT-B/32'
  STRIDE: 16
  CROSS_DEPTH: 4
  EMBED_DIM: 512
  HEAD: 
    SDM_LOSS: True
    CLIP_LOSS: False
    ID_LOSS: True
    TRIPLET_LOSS: True
    
TRAIN:
  EPOCH: 40
  FREEZE_EPOCH: 0
  BATCH_SIZE: 64
  MODE: 'multigrained'
  NUM_INSTANCE: 4
  
  LR:
    BASE_LR : 1e-5
    DELAY: 5
    WARMUP_EPOCH: 5
    LR_FACTOR: 5.


EVAL:
  EPOCH: 1
