DATA:
  SIZE: [384,128]
  BPE_PATH: './data/bpe_simple_vocab_16e6.txt.gz'
MODEL:
  NAME: 'clip_multiview_gnn'
  PRETRAINED: 'ViT-B/16'
  STRIDE: 16
  HEAD: 
    SDM_LOSS: True
    CLIP_LOSS: False
    SIMSIAM_LOSS: True

TRAIN:
  EPOCH: 100
  FREEZE_EPOCH: 0
  BATCH_SIZE: 32
  MODE: 'clip_multiview_gnn'
  DISCRIMINATOR: True
  ADV_COEFF: 0.4
  IN_FEATURES: 512
  NODE_FEATURES: 512
  EDGE_FEATURES: 512

  LR:
    BASE_LR : 5e-5
    DELAY: 5
    WARMUP_EPOCH: 5

EVAL:
  EPOCH: 1