DATA:
  SIZE: [384,128]
  BPE_PATH: './data/bpe_simple_vocab_16e6.txt.gz'
  TRAIN_JSON_PATH: 'reid_noun_chunks.json'
  MAX_NOUN_CHUNKS: 6
MODEL:
  NAME: 'clip_multi_prompt'
  PRETRAINED: 'ViT-B/16'
  STRIDE: 16
  HEAD: 
    SDM_LOSS: True
    CLIP_LOSS: False

TRAIN:
  EPOCH: 40
  FREEZE_EPOCH: 0
  BATCH_SIZE: 64
  MODE: 'clip_multi_prompt'

  LR:
    BASE_LR : 5e-5
    DELAY: 5
    WARMUP_EPOCH: 5

EVAL:
  EPOCH: 1

TEST:
  RESTORE_FROM: ./checkpoints/checkpoint_clip_multiprompt.pth
